/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sages.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Currencies (map type) */
@org.apache.avro.specific.AvroGenerated
public class Currencies extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1186741990598797480L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Currencies\",\"namespace\":\"com.sages.schema\",\"doc\":\"Currencies (map type)\",\"fields\":[{\"name\":\"currencies\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"doc\":\"currency mapping\",\"default\":{\"USD\":\"United State Dollars\",\"PLN\":\"Polish Zloty\"}},{\"name\":\"swiftCodes\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"int\"}],\"doc\":\"optional map\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Currencies> ENCODER =
      new BinaryMessageEncoder<Currencies>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Currencies> DECODER =
      new BinaryMessageDecoder<Currencies>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Currencies> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Currencies> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Currencies> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Currencies>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Currencies to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Currencies from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Currencies instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Currencies fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** currency mapping */
   private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> currencies;
  /** optional map */
   private java.util.Map<java.lang.CharSequence,java.lang.Integer> swiftCodes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Currencies() {}

  /**
   * All-args constructor.
   * @param currencies currency mapping
   * @param swiftCodes optional map
   */
  public Currencies(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> currencies, java.util.Map<java.lang.CharSequence,java.lang.Integer> swiftCodes) {
    this.currencies = currencies;
    this.swiftCodes = swiftCodes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return currencies;
    case 1: return swiftCodes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: currencies = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 1: swiftCodes = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'currencies' field.
   * @return currency mapping
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getCurrencies() {
    return currencies;
  }


  /**
   * Sets the value of the 'currencies' field.
   * currency mapping
   * @param value the value to set.
   */
  public void setCurrencies(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.currencies = value;
  }

  /**
   * Gets the value of the 'swiftCodes' field.
   * @return optional map
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getSwiftCodes() {
    return swiftCodes;
  }


  /**
   * Sets the value of the 'swiftCodes' field.
   * optional map
   * @param value the value to set.
   */
  public void setSwiftCodes(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.swiftCodes = value;
  }

  /**
   * Creates a new Currencies RecordBuilder.
   * @return A new Currencies RecordBuilder
   */
  public static com.sages.schema.Currencies.Builder newBuilder() {
    return new com.sages.schema.Currencies.Builder();
  }

  /**
   * Creates a new Currencies RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Currencies RecordBuilder
   */
  public static com.sages.schema.Currencies.Builder newBuilder(com.sages.schema.Currencies.Builder other) {
    if (other == null) {
      return new com.sages.schema.Currencies.Builder();
    } else {
      return new com.sages.schema.Currencies.Builder(other);
    }
  }

  /**
   * Creates a new Currencies RecordBuilder by copying an existing Currencies instance.
   * @param other The existing instance to copy.
   * @return A new Currencies RecordBuilder
   */
  public static com.sages.schema.Currencies.Builder newBuilder(com.sages.schema.Currencies other) {
    if (other == null) {
      return new com.sages.schema.Currencies.Builder();
    } else {
      return new com.sages.schema.Currencies.Builder(other);
    }
  }

  /**
   * RecordBuilder for Currencies instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Currencies>
    implements org.apache.avro.data.RecordBuilder<Currencies> {

    /** currency mapping */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> currencies;
    /** optional map */
    private java.util.Map<java.lang.CharSequence,java.lang.Integer> swiftCodes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sages.schema.Currencies.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.currencies)) {
        this.currencies = data().deepCopy(fields()[0].schema(), other.currencies);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.swiftCodes)) {
        this.swiftCodes = data().deepCopy(fields()[1].schema(), other.swiftCodes);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Currencies instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sages.schema.Currencies other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.currencies)) {
        this.currencies = data().deepCopy(fields()[0].schema(), other.currencies);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.swiftCodes)) {
        this.swiftCodes = data().deepCopy(fields()[1].schema(), other.swiftCodes);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'currencies' field.
      * currency mapping
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getCurrencies() {
      return currencies;
    }


    /**
      * Sets the value of the 'currencies' field.
      * currency mapping
      * @param value The value of 'currencies'.
      * @return This builder.
      */
    public com.sages.schema.Currencies.Builder setCurrencies(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.currencies = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'currencies' field has been set.
      * currency mapping
      * @return True if the 'currencies' field has been set, false otherwise.
      */
    public boolean hasCurrencies() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'currencies' field.
      * currency mapping
      * @return This builder.
      */
    public com.sages.schema.Currencies.Builder clearCurrencies() {
      currencies = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'swiftCodes' field.
      * optional map
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getSwiftCodes() {
      return swiftCodes;
    }


    /**
      * Sets the value of the 'swiftCodes' field.
      * optional map
      * @param value The value of 'swiftCodes'.
      * @return This builder.
      */
    public com.sages.schema.Currencies.Builder setSwiftCodes(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[1], value);
      this.swiftCodes = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'swiftCodes' field has been set.
      * optional map
      * @return True if the 'swiftCodes' field has been set, false otherwise.
      */
    public boolean hasSwiftCodes() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'swiftCodes' field.
      * optional map
      * @return This builder.
      */
    public com.sages.schema.Currencies.Builder clearSwiftCodes() {
      swiftCodes = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Currencies build() {
      try {
        Currencies record = new Currencies();
        record.currencies = fieldSetFlags()[0] ? this.currencies : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[0]);
        record.swiftCodes = fieldSetFlags()[1] ? this.swiftCodes : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Currencies>
    WRITER$ = (org.apache.avro.io.DatumWriter<Currencies>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Currencies>
    READER$ = (org.apache.avro.io.DatumReader<Currencies>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.currencies.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e0: this.currencies.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.CharSequence v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.swiftCodes == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size1 = this.swiftCodes.size();
      out.writeMapStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.util.Map.Entry<java.lang.CharSequence, java.lang.Integer> e1: this.swiftCodes.entrySet()) {
        actualSize1++;
        out.startItem();
        out.writeString(e1.getKey());
        java.lang.Integer v1 = e1.getValue();
        out.writeInt(v1);
      }
      out.writeMapEnd();
      if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.currencies; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
        this.currencies = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.CharSequence v0 = null;
          v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
          m0.put(k0, v0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.swiftCodes = null;
      } else {
        long size1 = in.readMapStart();
        java.util.Map<java.lang.CharSequence,java.lang.Integer> m1 = this.swiftCodes; // Need fresh name due to limitation of macro system
        if (m1 == null) {
          m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.Integer>((int)size1);
          this.swiftCodes = m1;
        } else m1.clear();
        for ( ; 0 < size1; size1 = in.mapNext()) {
          for ( ; size1 != 0; size1--) {
            java.lang.CharSequence k1 = null;
            k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
            java.lang.Integer v1 = null;
            v1 = in.readInt();
            m1.put(k1, v1);
          }
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.currencies; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
            this.currencies = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.CharSequence v0 = null;
              v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
              m0.put(k0, v0);
            }
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.swiftCodes = null;
          } else {
            long size1 = in.readMapStart();
            java.util.Map<java.lang.CharSequence,java.lang.Integer> m1 = this.swiftCodes; // Need fresh name due to limitation of macro system
            if (m1 == null) {
              m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.Integer>((int)size1);
              this.swiftCodes = m1;
            } else m1.clear();
            for ( ; 0 < size1; size1 = in.mapNext()) {
              for ( ; size1 != 0; size1--) {
                java.lang.CharSequence k1 = null;
                k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
                java.lang.Integer v1 = null;
                v1 = in.readInt();
                m1.put(k1, v1);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










