/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sages.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Transaction 4 (with enum type) */
@org.apache.avro.specific.AvroGenerated
public class Transaction4 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7899502565561307413L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Transaction4\",\"namespace\":\"com.sages.schema\",\"doc\":\"Transaction 4 (with enum type)\",\"fields\":[{\"name\":\"transactionType\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionType\",\"symbols\":[\"CREDIT\",\"DEBIT\",\"UNKNOWN\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Transaction4> ENCODER =
      new BinaryMessageEncoder<Transaction4>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Transaction4> DECODER =
      new BinaryMessageDecoder<Transaction4>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Transaction4> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Transaction4> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Transaction4> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Transaction4>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Transaction4 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Transaction4 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Transaction4 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Transaction4 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.sages.schema.TransactionType transactionType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Transaction4() {}

  /**
   * All-args constructor.
   * @param transactionType The new value for transactionType
   */
  public Transaction4(com.sages.schema.TransactionType transactionType) {
    this.transactionType = transactionType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionType = (com.sages.schema.TransactionType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return The value of the 'transactionType' field.
   */
  public com.sages.schema.TransactionType getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * @param value the value to set.
   */
  public void setTransactionType(com.sages.schema.TransactionType value) {
    this.transactionType = value;
  }

  /**
   * Creates a new Transaction4 RecordBuilder.
   * @return A new Transaction4 RecordBuilder
   */
  public static com.sages.schema.Transaction4.Builder newBuilder() {
    return new com.sages.schema.Transaction4.Builder();
  }

  /**
   * Creates a new Transaction4 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Transaction4 RecordBuilder
   */
  public static com.sages.schema.Transaction4.Builder newBuilder(com.sages.schema.Transaction4.Builder other) {
    if (other == null) {
      return new com.sages.schema.Transaction4.Builder();
    } else {
      return new com.sages.schema.Transaction4.Builder(other);
    }
  }

  /**
   * Creates a new Transaction4 RecordBuilder by copying an existing Transaction4 instance.
   * @param other The existing instance to copy.
   * @return A new Transaction4 RecordBuilder
   */
  public static com.sages.schema.Transaction4.Builder newBuilder(com.sages.schema.Transaction4 other) {
    if (other == null) {
      return new com.sages.schema.Transaction4.Builder();
    } else {
      return new com.sages.schema.Transaction4.Builder(other);
    }
  }

  /**
   * RecordBuilder for Transaction4 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Transaction4>
    implements org.apache.avro.data.RecordBuilder<Transaction4> {

    private com.sages.schema.TransactionType transactionType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sages.schema.Transaction4.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[0].schema(), other.transactionType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Transaction4 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sages.schema.Transaction4 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[0].schema(), other.transactionType);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'transactionType' field.
      * @return The value.
      */
    public com.sages.schema.TransactionType getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public com.sages.schema.Transaction4.Builder setTransactionType(com.sages.schema.TransactionType value) {
      validate(fields()[0], value);
      this.transactionType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * @return This builder.
      */
    public com.sages.schema.Transaction4.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Transaction4 build() {
      try {
        Transaction4 record = new Transaction4();
        record.transactionType = fieldSetFlags()[0] ? this.transactionType : (com.sages.schema.TransactionType) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Transaction4>
    WRITER$ = (org.apache.avro.io.DatumWriter<Transaction4>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Transaction4>
    READER$ = (org.apache.avro.io.DatumReader<Transaction4>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.transactionType.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionType = com.sages.schema.TransactionType.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionType = com.sages.schema.TransactionType.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










