spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      bootstrap-servers: http://172.17.0.1:29092, http://172.17.0.1:39092, http://172.17.0.1:49092