spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      value-serializer:  io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: http://kafka-1:29092, http://kafka-2:39092, http://kafka-3:49092
    properties:
      schema.registry.url: http://schema-registry:8081