spring:
  kafka:
    streams:
      application-id: "transaction_processor"
      bootstrap-servers: http://kafka-1:29092, http://kafka-2:39092, http://kafka-3:49092
      state-dir: "/tmp/transaction_processor/instance2"
      replication-factor: 2
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$DoubleSerde

