/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sages.schema.evolution.not.forward;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7963930330803593097L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionV2\",\"namespace\":\"com.sages.schema.evolution.not.forward\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"long\"},{\"name\":\"transactionValue\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionV2> ENCODER =
      new BinaryMessageEncoder<TransactionV2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionV2> DECODER =
      new BinaryMessageDecoder<TransactionV2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionV2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionV2>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionV2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionV2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionV2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long transactionId;
   private double transactionValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionV2() {}

  /**
   * All-args constructor.
   * @param transactionId The new value for transactionId
   * @param transactionValue The new value for transactionValue
   */
  public TransactionV2(java.lang.Long transactionId, java.lang.Double transactionValue) {
    this.transactionId = transactionId;
    this.transactionValue = transactionValue;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return transactionValue;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = (java.lang.Long)value$; break;
    case 1: transactionValue = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public long getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(long value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'transactionValue' field.
   * @return The value of the 'transactionValue' field.
   */
  public double getTransactionValue() {
    return transactionValue;
  }


  /**
   * Sets the value of the 'transactionValue' field.
   * @param value the value to set.
   */
  public void setTransactionValue(double value) {
    this.transactionValue = value;
  }

  /**
   * Creates a new TransactionV2 RecordBuilder.
   * @return A new TransactionV2 RecordBuilder
   */
  public static com.sages.schema.evolution.not.forward.TransactionV2.Builder newBuilder() {
    return new com.sages.schema.evolution.not.forward.TransactionV2.Builder();
  }

  /**
   * Creates a new TransactionV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionV2 RecordBuilder
   */
  public static com.sages.schema.evolution.not.forward.TransactionV2.Builder newBuilder(com.sages.schema.evolution.not.forward.TransactionV2.Builder other) {
    if (other == null) {
      return new com.sages.schema.evolution.not.forward.TransactionV2.Builder();
    } else {
      return new com.sages.schema.evolution.not.forward.TransactionV2.Builder(other);
    }
  }

  /**
   * Creates a new TransactionV2 RecordBuilder by copying an existing TransactionV2 instance.
   * @param other The existing instance to copy.
   * @return A new TransactionV2 RecordBuilder
   */
  public static com.sages.schema.evolution.not.forward.TransactionV2.Builder newBuilder(com.sages.schema.evolution.not.forward.TransactionV2 other) {
    if (other == null) {
      return new com.sages.schema.evolution.not.forward.TransactionV2.Builder();
    } else {
      return new com.sages.schema.evolution.not.forward.TransactionV2.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionV2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionV2>
    implements org.apache.avro.data.RecordBuilder<TransactionV2> {

    private long transactionId;
    private double transactionValue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sages.schema.evolution.not.forward.TransactionV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionValue)) {
        this.transactionValue = data().deepCopy(fields()[1].schema(), other.transactionValue);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sages.schema.evolution.not.forward.TransactionV2 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionValue)) {
        this.transactionValue = data().deepCopy(fields()[1].schema(), other.transactionValue);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public long getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.sages.schema.evolution.not.forward.TransactionV2.Builder setTransactionId(long value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.sages.schema.evolution.not.forward.TransactionV2.Builder clearTransactionId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionValue' field.
      * @return The value.
      */
    public double getTransactionValue() {
      return transactionValue;
    }


    /**
      * Sets the value of the 'transactionValue' field.
      * @param value The value of 'transactionValue'.
      * @return This builder.
      */
    public com.sages.schema.evolution.not.forward.TransactionV2.Builder setTransactionValue(double value) {
      validate(fields()[1], value);
      this.transactionValue = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionValue' field has been set.
      * @return True if the 'transactionValue' field has been set, false otherwise.
      */
    public boolean hasTransactionValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionValue' field.
      * @return This builder.
      */
    public com.sages.schema.evolution.not.forward.TransactionV2.Builder clearTransactionValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionV2 build() {
      try {
        TransactionV2 record = new TransactionV2();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.Long) defaultValue(fields()[0]);
        record.transactionValue = fieldSetFlags()[1] ? this.transactionValue : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionV2>
    READER$ = (org.apache.avro.io.DatumReader<TransactionV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.transactionId);

    out.writeDouble(this.transactionValue);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionId = in.readLong();

      this.transactionValue = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionId = in.readLong();
          break;

        case 1:
          this.transactionValue = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










